INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (1, 'Arizona', 'Cardinals', 'ARI');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (2, 'Atlanta', 'Falcons', 'ATL');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (3, 'Baltimore', 'Ravens', 'BAL');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (4, 'Buffalo', 'Bills', 'BUF');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (5, 'Carolina', 'Panthers', 'CAR');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (6, 'Chicago', 'Bears', 'CHI');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (7, 'Cincinnati', 'Bengals', 'CIN');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (8, 'Cleveland', 'Browns', 'CLE');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (9, 'Dallas', 'Cowboys', 'DAL');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (10, 'Denver', 'Broncos', 'DEN');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (11, 'Detroit', 'Lions', 'DET');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (12, 'Green Bay', 'Packers', 'GB');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (13, 'Houston', 'Texans', 'HOU');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (14, 'Indianapolis', 'Colts', 'IND');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (15, 'Jacksonville', 'Jaguars', 'JAX');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (16, 'Kansas City', 'Chiefs', 'KC');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (17, 'Los Angeles', 'Chargers', 'LAC');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (18, 'Los Angeles', 'Rams', 'LAR');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (19, 'Miami', 'Dolphins', 'MIA');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (20, 'Minnesota', 'Vikings', 'MIN');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (21, 'New England', 'Patriots', 'NE');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (22, 'New Orleans', 'Saints', 'NO');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (23, 'New York', 'Giants', 'NYG');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (24, 'New York', 'Jets', 'NYJ');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (25, 'Oakland', 'Raiders', 'OAK');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (26, 'Philadelphia', 'Eagles', 'PHI');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (27, 'Pittsburgh', 'Steelers', 'PIT');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (28, 'San Fransisco', '49ers', 'SF');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (29, 'Seattle', 'Seahawks', 'SEA');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (30, 'Tampa Bay', 'Buccaneers', 'TB');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (31, 'Tennessee', 'Titans', 'TEN');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (32, 'Washington', 'Redskins', 'WAS');
