INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (1, 'Arizona', 'Cardinals', 'ARI');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (2, 'Atlanta', 'Falcons', 'ATL');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (3, 'Baltimore', 'Ravens', 'BAL');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (4, 'Buffalo', 'Bills', 'BUF');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (5, 'Carolina', 'Panthers', 'CAR');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (6, 'Chicago', 'Bears', 'CHI');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (7, 'Cincinnati', 'Bengals', 'CIN');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (8, 'Cleveland', 'Browns', 'CLE');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (9, 'Dallas', 'Cowboys', 'DAL');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (10, 'Denver', 'Broncos', 'DEN');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (11, 'Detroit', 'Lions', 'DET');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (12, 'Green Bay', 'Packers', 'GB');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (13, 'Houston', 'Texans', 'HOU');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (14, 'Indianapolis', 'Colts', 'IND');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (15, 'Jacksonville', 'Jaguars', 'JAX');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (16, 'Kansas City', 'Chiefs', 'KC');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (17, 'Los Angeles', 'Chargers', 'LAC');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (18, 'Los Angeles', 'Rams', 'LAR');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (19, 'Miami', 'Dolphins', 'MIA');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (20, 'Minnesota', 'Vikings', 'MIN');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (21, 'New England', 'Patriots', 'NE');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (22, 'New Orleans', 'Saints', 'NO');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (23, 'New York', 'Giants', 'NYG');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (24, 'New York', 'Jets', 'NYJ');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (25, 'Oakland', 'Raiders', 'OAK');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (26, 'Philadelphia', 'Eagles', 'PHI');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (27, 'Pittsburgh', 'Steelers', 'PIT');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (28, 'San Fransisco', '49ers', 'SF');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (29, 'Seattle', 'Seahawks', 'SEA');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (30, 'Tampa Bay', 'Buccaneers', 'TB');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (31, 'Tennessee', 'Titans', 'TEN');
INSERT INTO TEAM (TEAM_ID, CITY, NAME, ABBREVIATION) 
VALUES (32, 'Washington', 'Redskins', 'WAS');

insert into player (player_id, name, position, team_id) values(1, 'Saquon Barkley', 'RB', 23);
insert into player (player_id, name, position, team_id) values(2, 'Alvin Kamara', 'RB', 22);
insert into player (player_id, name, position, team_id) values(3, 'Christian McCaffrey', 'RB', 5);
insert into player (player_id, name, position, team_id) values(4, 'Ezekiel Elliott', 'RB', 9);
insert into player (player_id, name, position, team_id) values(5, 'David Johnson', 'RB', 1);
insert into player (player_id, name, position, team_id) values(6, 'DeAndre Hopkins', 'WR', 13);
insert into player (player_id, name, position, team_id) values(7, 'Le\'Veon Bell', 'RB', 24);
insert into player (player_id, name, position, team_id) values(8, 'Davante Adams', 'WR', 12);
insert into player (player_id, name, position, team_id) values(9, 'Nick Chubb', 'RB', 8);
insert into player (player_id, name, position, team_id) values(10, 'James Conner', 'RB', 27);
insert into player (player_id, name, position, team_id) values(11, 'Julio Jones', 'WR', 2);
insert into player (player_id, name, position, team_id) values(12, 'Odell Beckham Jr.', 'WR', 8);
insert into player (player_id, name, position, team_id) values(13, 'Michael Thomas', 'WR', 22);
insert into player (player_id, name, position, team_id) values(14, 'Travis Kelce', 'TE', 16);
insert into player (player_id, name, position, team_id) values(15, 'Patrick Mahomes', 'QB', 16);
insert into player (player_id, name, position, team_id) values(16, 'JuJu Smith-Schuster', 'WR', 27);
insert into player (player_id, name, position, team_id) values(17, 'Dalvin Cook', 'RB', 20);
insert into player (player_id, name, position, team_id) values(18, 'Joe Mixon', 'RB', 7);
insert into player (player_id, name, position, team_id) values(19, 'Todd Gurley II', 'RB', 18);
insert into player (player_id, name, position, team_id) values(20, 'George Kittle', 'TE', 28);
insert into player (player_id, name, position, team_id) values(21, 'Tyreek Hill', 'WR', 16);
insert into player (player_id, name, position, team_id) values(22, 'Mike Evans', 'WR', 30);
insert into player (player_id, name, position, team_id) values(23, 'Antonio Brown', 'WR', 25);
insert into player (player_id, name, position, team_id) values(24, 'Damien Williams', 'RB', 16);
insert into player (player_id, name, position, team_id) values(25, 'Melvin Gordon III', 'RB', 17);
insert into player (player_id, name, position, team_id) values(26, 'Zach Ertz', 'TE', 26);
insert into player (player_id, name, position, team_id) values(27, 'Marlon Mack', 'RB', 14);
insert into player (player_id, name, position, team_id) values(28, 'Keenan Allen', 'WR', 17);
insert into player (player_id, name, position, team_id) values(29, 'Adam Thielen', 'WR', 20);
insert into player (player_id, name, position, team_id) values(30, 'T.Y. Hilton', 'WR', 14);
insert into player (player_id, name, position, team_id) values(31, 'Amari Cooper', 'WR', 9);
insert into player (player_id, name, position, team_id) values(32, 'Aaron Jones', 'RB', 12);
insert into player (player_id, name, position, team_id) values(33, 'Derrick Henry', 'RB', 31);
insert into player (player_id, name, position, team_id) values(34, 'Devonta Freeman', 'RB', 2);
insert into player (player_id, name, position, team_id) values(35, 'Kerryon Johnson', 'RB', 11);
insert into player (player_id, name, position, team_id) values(36, 'Leonard Fournette', 'RB', 15);
insert into player (player_id, name, position, team_id) values(37, 'Stefon Diggs', 'WR', 20);
insert into player (player_id, name, position, team_id) values(38, 'Robert Woods', 'WR', 18);
insert into player (player_id, name, position, team_id) values(39, 'Deshaun Watson', 'QB', 13);
insert into player (player_id, name, position, team_id) values(40, 'Aaron Rodgers', 'QB', 12);
insert into player (player_id, name, position, team_id) values(41, 'Brandin Cooks', 'WR', 18);
insert into player (player_id, name, position, team_id) values(42, 'Julian Edelman', 'WR', 21);
insert into player (player_id, name, position, team_id) values(43, 'Chris Godwin', 'WR', 30);
insert into player (player_id, name, position, team_id) values(44, 'Josh Jacobs', 'RB', 25);
insert into player (player_id, name, position, team_id) values(45, 'Kenny Golladay', 'WR', 11);
insert into player (player_id, name, position, team_id) values(46, 'Mark Ingram II', 'RB', 3);
insert into player (player_id, name, position, team_id) values(47, 'Baker Mayfield', 'QB', 8);
insert into player (player_id, name, position, team_id) values(48, 'Sony Michel', 'RB', 21);
insert into player (player_id, name, position, team_id) values(49, 'O.J. Howard', 'TE', 30);
insert into player (player_id, name, position, team_id) values(50, 'Andrew Luck', 'QB', 14);
insert into player (player_id, name, position, team_id) values(51, 'Phillip Lindsay', 'RB', 10);
insert into player (player_id, name, position, team_id) values(52, 'David Montgomery', 'RB', 6);
insert into player (player_id, name, position, team_id) values(53, 'Evan Engram', 'TE', 23);
insert into player (player_id, name, position, team_id) values(54, 'Hunter Henry', 'TE', 17);
insert into player (player_id, name, position, team_id) values(55, 'Chris Carson', 'RB', 29);
insert into player (player_id, name, position, team_id) values(56, 'Allen Robinson II', 'WR', 6);
insert into player (player_id, name, position, team_id) values(57, 'Tyler Lockett', 'WR', 29);
insert into player (player_id, name, position, team_id) values(58, 'Mike Williams', 'WR', 17);
insert into player (player_id, name, position, team_id) values(59, 'Matt Ryan', 'QB', 2);
insert into player (player_id, name, position, team_id) values(60, 'Chicago', 'DEF', 6);
insert into player (player_id, name, position, team_id) values(61, 'Cooper Kupp', 'WR', 18);
insert into player (player_id, name, position, team_id) values(62, 'Tyler Boyd', 'WR', 7);
insert into player (player_id, name, position, team_id) values(63, 'Jared Cook', 'TE', 22);
insert into player (player_id, name, position, team_id) values(64, 'Russell Wilson', 'QB', 29);
insert into player (player_id, name, position, team_id) values(65, 'Calvin Ridley', 'WR', 2);
insert into player (player_id, name, position, team_id) values(66, 'Drew Brees', 'QB', 22);
insert into player (player_id, name, position, team_id) values(67, 'Jarvis Landry', 'WR', 8);
insert into player (player_id, name, position, team_id) values(68, 'A.J. Green', 'WR', 7);
insert into player (player_id, name, position, team_id) values(69, 'Los Angeles', 'DEF', 18);
insert into player (player_id, name, position, team_id) values(70, 'Tevin Coleman', 'RB', 28);
insert into player (player_id, name, position, team_id) values(71, 'Cam Newton', 'QB', 5);
insert into player (player_id, name, position, team_id) values(72, 'Alshon Jeffery', 'WR', 26);
insert into player (player_id, name, position, team_id) values(73, 'Eric Ebron', 'TE', 14);
insert into player (player_id, name, position, team_id) values(74, 'Greg Zuerlein', 'K', 18);
insert into player (player_id, name, position, team_id) values(75, 'Tarik Cohen', 'RB', 6);
insert into player (player_id, name, position, team_id) values(76, 'D.J. Moore', 'WR', 5);
insert into player (player_id, name, position, team_id) values(77, 'Kenyan Drake', 'RB', 19);
insert into player (player_id, name, position, team_id) values(78, 'Jacksonville', 'DEF', 15);
insert into player (player_id, name, position, team_id) values(79, 'James White', 'RB', 21);
insert into player (player_id, name, position, team_id) values(80, 'Robby Anderson', 'WR', 24);
insert into player (player_id, name, position, team_id) values(81, 'Carson Wentz', 'QB', 26);
insert into player (player_id, name, position, team_id) values(82, 'Kyler Murray', 'QB', 1);
insert into player (player_id, name, position, team_id) values(83, 'Harrison Butker', 'K', 16);
insert into player (player_id, name, position, team_id) values(84, 'Baltimore', 'DEF', 3);
insert into player (player_id, name, position, team_id) values(85, 'Justin Tucker', 'K', 3);
insert into player (player_id, name, position, team_id) values(86, 'David Njoku', 'TE', 8);
insert into player (player_id, name, position, team_id) values(87, 'Vance McDonald', 'TE', 27);
insert into player (player_id, name, position, team_id) values(88, 'Minnesota', 'DEF', 20);
insert into player (player_id, name, position, team_id) values(89, 'Will Fuller V', 'WR', 13);
insert into player (player_id, name, position, team_id) values(90, 'Jordan Howard', 'RB', 26);
insert into player (player_id, name, position, team_id) values(91, 'Stephen Gostkowski', 'K', 21);
insert into player (player_id, name, position, team_id) values(92, 'Christian Kirk', 'WR', 1);
insert into player (player_id, name, position, team_id) values(93, 'Corey Davis', 'WR', 31);
insert into player (player_id, name, position, team_id) values(94, 'Sammy Watkins', 'WR', 16);
insert into player (player_id, name, position, team_id) values(95, 'Lamar Miller', 'RB', 13);
insert into player (player_id, name, position, team_id) values(96, 'Josh Gordon', 'WR', 21);
insert into player (player_id, name, position, team_id) values(97, 'Miles Sanders', 'RB', 26);
insert into player (player_id, name, position, team_id) values(98, 'Latavius Murray', 'RB', 22);
insert into player (player_id, name, position, team_id) values(99, 'Jared Goff', 'QB', 18);
insert into player (player_id, name, position, team_id) values(100, 'Los Angeles', 'DEF', 17);
insert into player (player_id, name, position, team_id) values(101, 'Derrius Guice', 'RB', 32);
insert into player (player_id, name, position, team_id) values(102, 'Wil Lutz', 'K', 22);
insert into player (player_id, name, position, team_id) values(103, 'Dede Westbrook', 'WR', 15);
insert into player (player_id, name, position, team_id) values(104, 'Cleveland', 'DEF', 8);
insert into player (player_id, name, position, team_id) values(105, 'Tom Brady', 'QB', 21);
insert into player (player_id, name, position, team_id) values(106, 'Curtis Samuel', 'WR', 5);
insert into player (player_id, name, position, team_id) values(107, 'Austin Ekeler', 'RB', 17);
insert into player (player_id, name, position, team_id) values(108, 'Sterling Shepard', 'WR', 23);
insert into player (player_id, name, position, team_id) values(109, 'Rashaad Penny', 'RB', 29);
insert into player (player_id, name, position, team_id) values(110, 'Austin Hooper', 'TE', 2);
insert into player (player_id, name, position, team_id) values(111, 'Duke Johnson Jr.', 'RB', 13);
insert into player (player_id, name, position, team_id) values(112, 'Ka\'imi Fairbairn', 'K', 13);
insert into player (player_id, name, position, team_id) values(113, 'Dante Pettis', 'WR', 28);
insert into player (player_id, name, position, team_id) values(114, 'Royce Freeman', 'RB', 10);
insert into player (player_id, name, position, team_id) values(115, 'Larry Fitzgerald', 'WR', 1);
insert into player (player_id, name, position, team_id) values(116, 'Marvin Jones Jr.', 'WR', 11);
insert into player (player_id, name, position, team_id) values(117, 'Kareem Hunt', 'RB', 8);
insert into player (player_id, name, position, team_id) values(118, 'Ben Roethlisberger', 'QB', 27);
insert into player (player_id, name, position, team_id) values(119, 'Lamar Jackson', 'QB', 3);
insert into player (player_id, name, position, team_id) values(120, 'Jason Witten', 'TE', 9);
insert into player (player_id, name, position, team_id) values(121, 'Houston', 'DEF', 13);
insert into player (player_id, name, position, team_id) values(122, 'Delanie Walker', 'TE', 31);
insert into player (player_id, name, position, team_id) values(123, 'Darrell Henderson Jr.', 'RB', 18);
insert into player (player_id, name, position, team_id) values(124, 'Dak Prescott', 'QB', 9);
insert into player (player_id, name, position, team_id) values(125, 'Nick Foles', 'QB', 15);
insert into player (player_id, name, position, team_id) values(126, 'LeSean McCoy', 'RB', 4);
insert into player (player_id, name, position, team_id) values(127, 'Jameis Winston', 'QB', 30);
insert into player (player_id, name, position, team_id) values(128, 'Matthew Stafford', 'QB', 11);
insert into player (player_id, name, position, team_id) values(129, 'Jerick McKinnon', 'RB', 28);
insert into player (player_id, name, position, team_id) values(130, 'New England', 'DEF', 21);
insert into player (player_id, name, position, team_id) values(131, 'Rob Gronkowski', 'TE', 21);
insert into player (player_id, name, position, team_id) values(132, 'Derek Carr', 'QB', 25);
insert into player (player_id, name, position, team_id) values(133, 'Philip Rivers', 'QB', 17);
insert into player (player_id, name, position, team_id) values(134, 'Kyle Rudolph', 'TE', 20);
insert into player (player_id, name, position, team_id) values(135, 'Ted Ginn Jr.', 'WR', 22);
insert into player (player_id, name, position, team_id) values(136, 'Keke Coutee', 'WR', 13);
insert into player (player_id, name, position, team_id) values(137, 'Randall Cobb', 'WR', 9);
insert into player (player_id, name, position, team_id) values(138, 'Courtland Sutton', 'WR', 10);
insert into player (player_id, name, position, team_id) values(139, 'DeSean Jackson', 'WR', 26);
insert into player (player_id, name, position, team_id) values(140, 'Rex Burkhead', 'RB', 21);
insert into player (player_id, name, position, team_id) values(141, 'Darwin Thompson', 'RB', 16);
insert into player (player_id, name, position, team_id) values(142, 'Emmanuel Sanders', 'WR', 10);
insert into player (player_id, name, position, team_id) values(143, 'Tony Pollard', 'RB', 9);
insert into player (player_id, name, position, team_id) values(144, 'Golden Tate', 'WR', 23);
insert into player (player_id, name, position, team_id) values(145, 'Adrian Peterson', 'RB', 32);
insert into player (player_id, name, position, team_id) values(146, 'N\'Keal Harry', 'WR', 21);
insert into player (player_id, name, position, team_id) values(147, 'Atlanta', 'DEF', 2);
insert into player (player_id, name, position, team_id) values(148, 'Tyler Eifert', 'TE', 7);
insert into player (player_id, name, position, team_id) values(149, 'Matt Breida', 'RB', 28);
insert into player (player_id, name, position, team_id) values(150, 'James Washington', 'WR', 27);
insert into player (player_id, name, position, team_id) values(151, 'Carolina', 'DEF', 5);
insert into player (player_id, name, position, team_id) values(152, 'New Orleans', 'DEF', 22);
insert into player (player_id, name, position, team_id) values(153, 'Carlos Hyde', 'RB', 16);
insert into player (player_id, name, position, team_id) values(154, 'Mitchell Trubisky', 'QB', 6);
insert into player (player_id, name, position, team_id) values(155, 'Mecole Hardman', 'WR', 16);
insert into player (player_id, name, position, team_id) values(156, 'Mark Andrews', 'TE', 3);
insert into player (player_id, name, position, team_id) values(157, 'Greg Olsen', 'TE', 5);
insert into player (player_id, name, position, team_id) values(158, 'Marquez Valdes-Scantling', 'WR', 12);
insert into player (player_id, name, position, team_id) values(159, 'Michael Gallup', 'WR', 9);
insert into player (player_id, name, position, team_id) values(160, 'DK Metcalf', 'WR', 29);
insert into player (player_id, name, position, team_id) values(161, 'Kenny Stills', 'WR', 19);
insert into player (player_id, name, position, team_id) values(162, 'Kirk Cousins', 'QB', 20);
insert into player (player_id, name, position, team_id) values(163, 'Kalen Ballage', 'RB', 19);
insert into player (player_id, name, position, team_id) values(164, 'Tre\'Quan Smith', 'WR', 22);
insert into player (player_id, name, position, team_id) values(165, 'Adam Humphries', 'WR', 31);
insert into player (player_id, name, position, team_id) values(166, 'C.J. Anderson', 'RB', 11);
insert into player (player_id, name, position, team_id) values(167, 'Robbie Gould', 'K', 28);
insert into player (player_id, name, position, team_id) values(168, 'Sam Darnold', 'QB', 24);
insert into player (player_id, name, position, team_id) values(169, 'Nelson Agholor', 'WR', 26);
insert into player (player_id, name, position, team_id) values(170, 'Green Bay', 'DEF', 12);
insert into player (player_id, name, position, team_id) values(171, 'Devin Funchess', 'WR', 14);
insert into player (player_id, name, position, team_id) values(172, 'D\'Onta Foreman', 'RB', 14);
insert into player (player_id, name, position, team_id) values(173, 'Trey Burton', 'TE', 6);
insert into player (player_id, name, position, team_id) values(174, 'Geronimo Allison', 'WR', 12);
insert into player (player_id, name, position, team_id) values(175, 'Jaylen Samuels', 'RB', 27);
insert into player (player_id, name, position, team_id) values(176, 'Nyheim Hines', 'RB', 14);
insert into player (player_id, name, position, team_id) values(177, 'Adam Vinatieri', 'K', 14);
insert into player (player_id, name, position, team_id) values(178, 'Justin Jackson', 'RB', 17);
insert into player (player_id, name, position, team_id) values(179, 'Mason Crosby', 'K', 12);
insert into player (player_id, name, position, team_id) values(180, 'Donte Moncrief', 'WR', 27);
insert into player (player_id, name, position, team_id) values(181, 'Pittsburgh', 'DEF', 27);
insert into player (player_id, name, position, team_id) values(182, 'Detroit', 'DEF', 11);
insert into player (player_id, name, position, team_id) values(183, 'Tyrell Williams', 'WR', 25);
insert into player (player_id, name, position, team_id) values(184, 'Peyton Barber', 'RB', 30);
insert into player (player_id, name, position, team_id) values(185, 'Damien Harris', 'RB', 21);
insert into player (player_id, name, position, team_id) values(186, 'Parris Campbell', 'WR', 14);
insert into player (player_id, name, position, team_id) values(187, 'Mohamed Sanu', 'WR', 2);
insert into player (player_id, name, position, team_id) values(188, 'Marquise Brown', 'WR', 3);
insert into player (player_id, name, position, team_id) values(189, 'Anthony Miller', 'WR', 6);
insert into player (player_id, name, position, team_id) values(190, 'Marquise Goodwin', 'WR', 28);
insert into player (player_id, name, position, team_id) values(191, 'T.J. Hockenson', 'TE', 11);
insert into player (player_id, name, position, team_id) values(192, 'Deebo Samuel', 'WR', 28);
insert into player (player_id, name, position, team_id) values(193, 'Mike Davis', 'RB', 6);
insert into player (player_id, name, position, team_id) values(194, 'Jimmy Graham', 'TE', 12);
insert into player (player_id, name, position, team_id) values(195, 'Devin Singletary', 'RB', 4);
insert into player (player_id, name, position, team_id) values(196, 'Ronald Jones II', 'RB', 30);
insert into player (player_id, name, position, team_id) values(197, 'Justice Hill', 'RB', 3);
insert into player (player_id, name, position, team_id) values(198, 'Jamison Crowder', 'WR', 24);
insert into player (player_id, name, position, team_id) values(199, 'Noah Fant', 'TE', 10);
insert into player (player_id, name, position, team_id) values(200, 'Dion Lewis', 'RB', 31);
insert into player (player_id, name, position, team_id) values(201, 'Alexander Mattison', 'RB', 20);
insert into player (player_id, name, position, team_id) values(202, 'Kansas City', 'DEF', 16);
insert into player (player_id, name, position, team_id) values(203, 'DeVante Parker', 'WR', 19);
insert into player (player_id, name, position, team_id) values(204, 'Jimmy Garoppolo', 'QB', 28);
insert into player (player_id, name, position, team_id) values(205, 'Dallas', 'DEF', 9);
insert into player (player_id, name, position, team_id) values(206, 'New York', 'DEF', 24);
insert into player (player_id, name, position, team_id) values(207, 'Darren Waller', 'TE', 25);
insert into player (player_id, name, position, team_id) values(208, 'Ito Smith', 'RB', 2);
insert into player (player_id, name, position, team_id) values(209, 'John Brown', 'WR', 4);
insert into player (player_id, name, position, team_id) values(210, 'Chris Herndon', 'TE', 24);
insert into player (player_id, name, position, team_id) values(211, 'Philadelphia', 'DEF', 26);
insert into player (player_id, name, position, team_id) values(212, 'Brandon McManus', 'K', 10);
insert into player (player_id, name, position, team_id) values(213, 'Josh Allen', 'QB', 4);
insert into player (player_id, name, position, team_id) values(214, 'Chris Boswell', 'K', 27);
insert into player (player_id, name, position, team_id) values(215, 'Jordan Reed', 'TE', 32);
insert into player (player_id, name, position, team_id) values(216, 'Greg Joseph', 'K', 8);
insert into player (player_id, name, position, team_id) values(217, 'Tennessee', 'DEF', 31);
insert into player (player_id, name, position, team_id) values(218, 'San Francisco', 'DEF', 28);
insert into player (player_id, name, position, team_id) values(219, 'Jack Doyle', 'TE', 14);
insert into player (player_id, name, position, team_id) values(220, 'Dallas Goedert', 'TE', 26);
insert into player (player_id, name, position, team_id) values(221, 'Denver', 'DEF', 10);
insert into player (player_id, name, position, team_id) values(222, 'Jason Myers', 'K', 29);
insert into player (player_id, name, position, team_id) values(223, 'Michael Badgley', 'K', 17);
insert into player (player_id, name, position, team_id) values(224, 'Buffalo', 'DEF', 4);
insert into player (player_id, name, position, team_id) values(225, 'Seattle', 'DEF', 29);
insert into player (player_id, name, position, team_id) values(226, 'Matt Prater', 'K', 11);
insert into player (player_id, name, position, team_id) values(227, 'Brett Maher', 'K', 9);
insert into player (player_id, name, position, team_id) values(228, 'Graham Gano', 'K', 5);
insert into player (player_id, name, position, team_id) values(229, 'Jake Elliott', 'K', 26);
insert into player (player_id, name, position, team_id) values(230, 'Indianapolis', 'DEF', 14);
insert into player (player_id, name, position, team_id) values(231, 'Aldrick Rosas', 'K', 23);
insert into player (player_id, name, position, team_id) values(232, 'Dan Bailey', 'K', 20);
insert into player (player_id, name, position, team_id) values(233, 'Giorgio Tavecchio', 'K', 2);
insert into player (player_id, name, position, team_id) values(234, 'DaeSean Hamilton', 'WR', 10);
insert into player (player_id, name, position, team_id) values(235, 'Jamaal Williams', 'RB', 12);
insert into player (player_id, name, position, team_id) values(236, 'Zay Jones', 'WR', 4);
insert into player (player_id, name, position, team_id) values(237, 'Chris Thompson', 'RB', 32);
insert into player (player_id, name, position, team_id) values(238, 'Jacoby Brissett', 'QB', 14);
insert into player (player_id, name, position, team_id) values(239, 'Andy Dalton', 'QB', 7);
insert into player (player_id, name, position, team_id) values(240, 'Quincy Enunwa', 'WR', 24);
insert into player (player_id, name, position, team_id) values(241, 'Giovani Bernard', 'RB', 7);
insert into player (player_id, name, position, team_id) values(242, 'Gerald Everett', 'TE', 18);
insert into player (player_id, name, position, team_id) values(243, 'Mike Gesicki', 'TE', 19);
insert into player (player_id, name, position, team_id) values(244, 'Malcolm Brown', 'RB', 18);
insert into player (player_id, name, position, team_id) values(245, 'Will Dissly', 'TE', 29);
insert into player (player_id, name, position, team_id) values(246, 'Taylor Gabriel', 'WR', 6);
insert into player (player_id, name, position, team_id) values(247, 'Albert Wilson', 'WR', 19);
insert into player (player_id, name, position, team_id) values(248, 'Rashard Higgins', 'WR', 8);
insert into player (player_id, name, position, team_id) values(249, 'Joe Flacco', 'QB', 10);
insert into player (player_id, name, position, team_id) values(250, 'Ty Montgomery', 'RB', 24);
insert into player (player_id, name, position, team_id) values(251, 'Jordan Thomas', 'TE', 13);
insert into player (player_id, name, position, team_id) values(252, 'Marcus Mariota', 'QB', 31);
insert into player (player_id, name, position, team_id) values(253, 'Danny Amendola', 'WR', 11);
insert into player (player_id, name, position, team_id) values(254, 'Ian Thomas', 'TE', 5);
insert into player (player_id, name, position, team_id) values(255, 'Elijah McGuire', 'RB', 24);
insert into player (player_id, name, position, team_id) values(256, 'Miles Boykin', 'WR', 3);
insert into player (player_id, name, position, team_id) values(257, 'Marqise Lee', 'WR', 15);
insert into player (player_id, name, position, team_id) values(258, 'Jalen Hurd', 'WR', 28);
insert into player (player_id, name, position, team_id) values(259, 'Robert Foster', 'WR', 4);
insert into player (player_id, name, position, team_id) values(260, 'Andy Isabella', 'WR', 1);
insert into player (player_id, name, position, team_id) values(261, 'Antonio Callaway', 'WR', 8);
insert into player (player_id, name, position, team_id) values(262, 'Trey Quinn', 'WR', 32);
insert into player (player_id, name, position, team_id) values(263, 'D.J. Chark Jr.', 'WR', 15);
insert into player (player_id, name, position, team_id) values(264, 'Ricky Seals-Jones', 'TE', 1);
insert into player (player_id, name, position, team_id) values(265, 'Ryan Fitzpatrick', 'QB', 19);
insert into player (player_id, name, position, team_id) values(266, 'Josh Doctson', 'WR', 32);
insert into player (player_id, name, position, team_id) values(267, 'A.J. Brown', 'WR', 31);
insert into player (player_id, name, position, team_id) values(268, 'Chase Edmonds', 'RB', 1);
insert into player (player_id, name, position, team_id) values(269, 'Josh Reynolds', 'WR', 18);
insert into player (player_id, name, position, team_id) values(270, 'KeeSean Johnson', 'WR', 1);
insert into player (player_id, name, position, team_id) values(271, 'Kenneth Dixon', 'RB', 3);
insert into player (player_id, name, position, team_id) values(272, 'John Ross III', 'WR', 7);
insert into player (player_id, name, position, team_id) values(273, 'Frank Gore', 'RB', 4);
insert into player (player_id, name, position, team_id) values(274, 'Ryan Succop', 'K', 31);
insert into player (player_id, name, position, team_id) values(275, 'Eli Manning', 'QB', 23);
insert into player (player_id, name, position, team_id) values(276, 'Diontae Johnson', 'WR', 27);
insert into player (player_id, name, position, team_id) values(277, 'Josh Rosen', 'QB', 19);
insert into player (player_id, name, position, team_id) values(278, 'Josh Lambo', 'K', 15);
insert into player (player_id, name, position, team_id) values(279, 'Stephen Hauschka', 'K', 4);
insert into player (player_id, name, position, team_id) values(280, 'Cameron Brate', 'TE', 30);
insert into player (player_id, name, position, team_id) values(281, 'Cairo Santos', 'K', 30);
insert into player (player_id, name, position, team_id) values(282, 'Benny Snell Jr.', 'RB', 27);
insert into player (player_id, name, position, team_id) values(283, 'Matt Bryant', 'K', 2);
insert into player (player_id, name, position, team_id) values(284, 'Case Keenum', 'QB', 32);
insert into player (player_id, name, position, team_id) values(285, 'Dwayne Haskins Jr.', 'QB', 32);
insert into player (player_id, name, position, team_id) values(286, 'Arizona', 'DEF', 1);
insert into player (player_id, name, position, team_id) values(287, 'Marshawn Lynch', 'RB', 25);
insert into player (player_id, name, position, team_id) values(288, 'Alex Collins', 'RB', 3);
insert into player (player_id, name, position, team_id) values(289, 'Jay Ajayi', 'RB', 26);
insert into player (player_id, name, position, team_id) values(290, 'T.J. Yeldon', 'RB', 4);
insert into player (player_id, name, position, team_id) values(291, 'Isaiah Crowell', 'RB', 25);
insert into player (player_id, name, position, team_id) values(292, 'Demaryius Thomas', 'WR', 21);
insert into player (player_id, name, position, team_id) values(293, 'C.J. Beathard', 'QB', 28);
insert into player (player_id, name, position, team_id) values(294, 'Jordy Nelson', 'WR', 25);
insert into player (player_id, name, position, team_id) values(295, 'Bilal Powell', 'RB', 24);
insert into player (player_id, name, position, team_id) values(296, 'Alex Smith', 'QB', 32);
insert into player (player_id, name, position, team_id) values(297, 'Brandon LaFell', 'WR', 25);
insert into player (player_id, name, position, team_id) values(298, 'Ben Watson', 'TE', 21);
insert into player (player_id, name, position, team_id) values(299, 'Michael Crabtree', 'WR', 1);
insert into player (player_id, name, position, team_id) values(300, 'Darren Sproles', 'RB', 26);


