INSERT INTO AVERAGE_AUCTION_VALUE(AVERAGE_AUCTION_VALUE_ID, AVERAGE_COST, PLATFORM, PLAYER_ID)
VALUES(1, 10.5, 'YAHOO', 1);
INSERT INTO AVERAGE_AUCTION_VALUE(AVERAGE_AUCTION_VALUE_ID, AVERAGE_COST, PLATFORM, PLAYER_ID)
VALUES(2, 8.5, 'ESPN', 1);
INSERT INTO AVERAGE_AUCTION_VALUE(AVERAGE_AUCTION_VALUE_ID, AVERAGE_COST, PLATFORM, PLAYER_ID)
VALUES(3, 61.3, 'YAHOO', 2);
