INSERT INTO AVERAGE_AUCTION_VALUE(AVERAGE_AUCTION_VALUE_ID, AVERAGE_COST, PLATFORM, PLAYER_ID)
VALUES(10001, 10.5, 'FANTRAX', 1);
INSERT INTO AVERAGE_AUCTION_VALUE(AVERAGE_AUCTION_VALUE_ID, AVERAGE_COST, PLATFORM, PLAYER_ID)
VALUES(10002, 8.5, 'ESPN', 1);
INSERT INTO AVERAGE_AUCTION_VALUE(AVERAGE_AUCTION_VALUE_ID, AVERAGE_COST, PLATFORM, PLAYER_ID)
VALUES(10003, 61.3, 'FANTRAX', 2);
